/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package burger.view;

import java.io.IOException;

/**
 *
 * @author sanda
 */
public class ViewOrdersForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewOrdersForm.class.getName());

    /**
     * Creates new form Home
     */
    public ViewOrdersForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        justAlable = new javax.swing.JButton();
        deliveredOrdersButten = new javax.swing.JButton();
        processingOrdersButten = new javax.swing.JButton();
        canceledOrdersButten = new javax.swing.JButton();
        exitButten = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomeBackground.jpeg"))); // NOI18N

        justAlable.setBackground(new java.awt.Color(255, 0, 0));
        justAlable.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        justAlable.setForeground(new java.awt.Color(255, 255, 255));
        justAlable.setText("View Orders");

        deliveredOrdersButten.setBackground(new java.awt.Color(255, 0, 0));
        deliveredOrdersButten.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        deliveredOrdersButten.setForeground(new java.awt.Color(255, 255, 255));
        deliveredOrdersButten.setText("Delivered Orders");
        deliveredOrdersButten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveredOrdersButtenActionPerformed(evt);
            }
        });

        processingOrdersButten.setBackground(new java.awt.Color(255, 0, 0));
        processingOrdersButten.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        processingOrdersButten.setForeground(new java.awt.Color(255, 255, 255));
        processingOrdersButten.setText("Processing Orders");
        processingOrdersButten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processingOrdersButtenActionPerformed(evt);
            }
        });

        canceledOrdersButten.setBackground(new java.awt.Color(255, 0, 0));
        canceledOrdersButten.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        canceledOrdersButten.setForeground(new java.awt.Color(255, 255, 255));
        canceledOrdersButten.setText("Canceled Orders");
        canceledOrdersButten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceledOrdersButtenActionPerformed(evt);
            }
        });

        exitButten.setBackground(new java.awt.Color(255, 0, 0));
        exitButten.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        exitButten.setForeground(new java.awt.Color(255, 255, 255));
        exitButten.setText("Exit");
        exitButten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(397, 397, 397)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deliveredOrdersButten, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(processingOrdersButten, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canceledOrdersButten, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitButten, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(justAlable, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(justAlable, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(deliveredOrdersButten, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(processingOrdersButten, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(canceledOrdersButten, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButten, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtenActionPerformed
        dispose();     
    }//GEN-LAST:event_exitButtenActionPerformed

    private void canceledOrdersButtenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceledOrdersButtenActionPerformed
        try {
            new CancledOrderForm().setVisible(true);
        } catch (IOException ex) {
            System.getLogger(ViewOrdersForm.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_canceledOrdersButtenActionPerformed

    private void processingOrdersButtenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processingOrdersButtenActionPerformed
        try {
            new PrepairingOrderForm().setVisible(true);
        } catch (IOException ex) {
            System.getLogger(ViewOrdersForm.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_processingOrdersButtenActionPerformed

    private void deliveredOrdersButtenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveredOrdersButtenActionPerformed
        try {
            new DeleverdOrderForm().setVisible(true);
        } catch (IOException ex) {
            System.getLogger(ViewOrdersForm.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_deliveredOrdersButtenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewOrdersForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton canceledOrdersButten;
    private javax.swing.JButton deliveredOrdersButten;
    private javax.swing.JButton exitButten;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton justAlable;
    private javax.swing.JButton processingOrdersButten;
    // End of variables declaration//GEN-END:variables
}
